"""add img column

Revision ID: 195f907bdcae
Revises: 
Create Date: 2024-09-25 13:17:05.172970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195f907bdcae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitcher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ROWID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))
        batch_op.alter_column('Name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('ERA',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('Yrs',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('IP',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('ASG',
               existing_type=sa.REAL(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.drop_column('G')
        batch_op.drop_column('BB')
        batch_op.drop_column('From')
        batch_op.drop_column('Name-additional')
        batch_op.drop_column('GF')
        batch_op.drop_column('BF')
        batch_op.drop_column('Rk')
        batch_op.drop_column('CG')
        batch_op.drop_column('ERA+')
        batch_op.drop_column('HBP')
        batch_op.drop_column('W-L%')
        batch_op.drop_column('WP')
        batch_op.drop_column('SV')
        batch_op.drop_column('W')
        batch_op.drop_column('SHO')
        batch_op.drop_column('SO')
        batch_op.drop_column('L')
        batch_op.drop_column('R')
        batch_op.drop_column('ER')
        batch_op.drop_column('To')
        batch_op.drop_column('BK')
        batch_op.drop_column('F')
        batch_op.drop_column('S')
        batch_op.drop_column('GS')
        batch_op.drop_column('H')
        batch_op.drop_column('C')
        batch_op.drop_column('HR')
        batch_op.drop_column('IBB')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitcher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IBB', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('HR', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('C', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('H', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('GS', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('S', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('F', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('BK', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('To', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('ER', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('R', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('L', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('SO', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('SHO', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('W', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('SV', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('WP', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('W-L%', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('HBP', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('ERA+', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('CG', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('Rk', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('BF', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('GF', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('Name-additional', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('From', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('BB', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('G', sa.REAL(), nullable=True))
        batch_op.alter_column('ASG',
               existing_type=sa.Boolean(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('IP',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Yrs',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('ERA',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('Name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('img')
        batch_op.drop_column('rk')
        batch_op.drop_column('ROWID')

    # ### end Alembic commands ###
